Created Overview 1 and edited index.md
UWC2-APIDOC/to-do-service-public pull request #101
Opened 2024-05-20 06:02 UTC by cherylkc

Created Overview 1 and added link to index.md

2024-05-20 13:34 UTC, cherylkc commented
I'm still not able to squash commits without force pushing, despite rebasing. Could it be a permissions issue?

2024-05-20 19:49 UTC, rbwatson commented
> I'm still not able to squash commits without force pushing, despite rebasing. Could it be a permissions issue?

That sounds normal.
When you rebase, you insert commits (from the changes that have been added since you created or last updated your branch) and so you're changing the history of that branch. This requires a force-push to "force" the new version of the branch's history back up to the cloud.

2024-05-21 23:03 UTC, rbwatson requested changes
Looks like a good start.
Just a couple of comments.
Be sure to use the Linter and build the docs from your feature branch.

2024-05-21 23:03 UTC, rbwatson commented on docs/overview-CG.md
> +> <span style="background-color:lightyellow;"> Set up your development environment using our [Before you start](tutorials/before-you-start-a-tutorial.md) tutorial to get the best results from the ser
```suggestion
<span style="background-color:lightyellow;"> Set up your development environment using our [Before you start](tutorials/before-you-start-a-tutorial.md) tutorial to get the best results from the service.</span>
```
this looks like it might have some extra characters...

Did the linter complain about the embedded HTML?

2024-05-21 23:03 UTC, rbwatson commented on docs/overview-CG.md
> +Visit www.to-do-service.com or drop us a line at to-do-service@productivity.com to schedule a demo.
I'm surprised that domain isn't in use.

2024-05-22 06:01 UTC, cherylkc commented on docs/overview-CG.md
> +> <span style="background-color:lightyellow;"> Set up your development environment using our [Before you start](tutorials/before-you-start-a-tutorial.md) tutorial to get the best results from the ser
- I did build the docs from my feature branch (overview-CG) and install a linter. 
- No complaints from the linter about any embedded HTML. 
- By 'extra characters', are you referring to the '>' ? - I added that to put that note in a block quote. I'm happy to remove it if you think it's not required.

2024-05-27 10:06 UTC, cherylkc commented
Hi Bob, I've updated the file and resolved all conflicts. Please review when you can.

2024-05-29 19:35 UTC, rbwatson approved these changes
Rebased and reviewed.
Fixed some links and converted example links to code format to not break link tests.
Squashed for merge.
LGTM

2024-05-29 19:36 UTC, merged