Joey Gallotta Reference topic: Get Task by User ID
UWC2-APIDOC/to-do-service-public pull request #37
Opened 2024-05-10 21:26 UTC by gallottaj

2024-05-10 21:26 UTC, gallottaj commented
Please review this new reference topic.

2024-05-10 21:47 UTC, rbwatson requested changes
This is a great start! I like the **Return body** example.

I tried the syntax in your **URL** example and it returned the task by the task's `id` instead of the `user_id`.

Check into using query parameters for how to get a task by the `user_id`, then update your new doc file.

2024-05-10 21:47 UTC, rbwatson commented on docs/api/task-get-task-by-user-id.md
> +| 404 | Error | Specified user record not found |
Would a 404 be returned because no task records were found that matched the query?

2024-05-10 21:47 UTC, rbwatson commented on docs/api/task-get-task-by-user-id.md
> +{server_url}/tasks/{user_id}
Is this the correct syntax to query by `user_id`?

2024-05-10 21:47 UTC, rbwatson commented on docs/api/task-get-task-by-user-id.md
> +| `user_id` | number | The ID of the user resource to which this task is assigned |
Because this is a query, could the description be rephrased to reflect how the parameter affects the query?

2024-05-10 21:47 UTC, rbwatson commented on docs/api/task.md
> +* [Get task by user ID](#task-get-task-by-user-id)
Double check the link. With the `#`, it will look for a heading in the current page with that title.

2024-05-20 14:06 UTC, rbwatson approved these changes
Rebased and squashed to merge

2024-05-20 14:06 UTC, merged