Joey Gallotta Tutorial topic: Update a User's Email
UWC2-APIDOC/to-do-service-public pull request #38
Opened 2024-05-10 21:43 UTC by gallottaj

2024-05-10 21:43 UTC, gallottaj commented
Please review this new tutorial topic.

2024-05-11 01:38 UTC, rbwatson requested changes
The tutorial looks pretty good.
A conclusion would make it clear that they've completed the task successfully.
The next steps are a nice touch.
I made some additional suggestions for clarity and brevity.

2024-05-11 01:38 UTC, rbwatson commented on docs/tutorials/update-user-email.md
> +In this tutorial, you'll learn the operations to call to update a user's email.
```suggestion
In this tutorial, you'll learn how to update a user's email.
```
Would this work?

2024-05-11 01:38 UTC, rbwatson commented on docs/tutorials/update-user-email.md
> +You can update an existing user's email in the To-Do service. To do so, `PUT` an [`email`](../api/user/id/email) resource containing the user's details.
```suggestion
You can update an existing user's email in the To-Do service.
```
The 2nd sentence might be confusing as the procedure that follows looks like you need to do more than that.

2024-05-11 01:38 UTC, rbwatson commented on docs/tutorials/update-user-email.md
> +
```suggestion

## Next steps

```
To make it clear that the paragraph isn't part of the procedure.

2024-05-20 14:10 UTC, rbwatson approved these changes
Rebased for merge.
Thanks for squashing!

2024-05-20 14:11 UTC, merged