My ref  topic
UWC2-APIDOC/to-do-service-public pull request #42
Opened 2024-05-11 10:29 UTC by writingteacher

2024-05-11 17:36 UTC, rbwatson requested changes
This is pretty good!
Please review my comments here and in https://canvas.uw.edu/courses/1715843/discussion_topics/8949983 and update the PR.
Thanks!

2024-05-11 17:36 UTC, rbwatson commented on api/to-do-db-source.json
Please remove this file from the pull request

2024-05-11 17:36 UTC, rbwatson commented on docs/api/user.md
> +Contains information about the users of the service. To have a task in the service, the user must be added to
I try to start new sentences on a new line to make future revisions easier to spot. Changes to the 2nd, 3rd, 4th... sentence are easier to spot and compare when the lines don't wrap in the display.

2024-05-11 17:36 UTC, rbwatson commented on docs/index.md
> +ABC reference. Ready to go.
I'm not sure what this refers to. Can you explain?

2024-05-11 17:36 UTC, rbwatson commented on docs/api/users-change-user-email.md
> +The Patch request updates the user's email address but does not change the other parameters in the [`user`](user) object.
With this reference topic, would there also be others like, Update user last_name, Update user first_name?
Or, could you change the topic title to **Update user properties** and show how what you describe in this topic for the email address could apply to any of the parameters by including the parameters that you want to change in the request body?

2024-05-11 17:36 UTC, rbwatson commented on docs/api/users-change-user-email.md
> +| `id` | number | The user's unique record ID. |
Is this required if you have it in the URL?

2024-05-11 17:36 UTC, rbwatson commented on docs/api/users-change-user-email.md
> +}
This example is different from what is listed in **Params** above. Is that intentional?
If `id` is is optional, then that should be mentioned in the **Params** section.

2024-05-11 17:36 UTC, rbwatson commented on docs/api/users-change-user-email.md
> +```
Great example!

2024-05-12 00:53 UTC, closed without merging

2024-05-12 02:35 UTC, rbwatson commented
Did you want to close the pull request or just indicate that you resolved the changes?
If the latter, please re-open the PR so I can merge it.
Thanks!

2024-05-12 03:11 UTC, writingteacher commented
Thanks Bob. I will close the pull request and try again.