Reference topic get task by id
UWC2-APIDOC/to-do-service-public pull request #47
Opened 2024-05-12 17:35 UTC by eapearce

I hope this is just the reference topic and a link change on the main tasks topic.

2024-05-12 23:04 UTC, rbwatson requested changes
Please review my comments and let me know if this and #46 are related or need to be merged in any specific order.

Thanks!

2024-05-12 23:04 UTC, rbwatson commented on docs/index.md
> +* [Searching for users](search-for-a-user.md)
```suggestion
* [Search for a user](search-for-a-user.md)
```

2024-05-12 23:04 UTC, rbwatson commented on docs/tutorials/get-a-user-by-id.md
> +      {{base_url}}/users?lid=1
```suggestion
      {{base_url}}/users?id=1
```
Typo?

2024-05-12 23:04 UTC, rbwatson commented on docs/tutorials/search-for-a-user.md
Is there a reason for the abbreviated format used in this tutorial?

2024-05-14 01:02 UTC, eapearce commented
Thank you! After reviewing the files, it looks like I was unsuccessful in trying to move some changes to the new branch, so some of the links that support the the tutorial topic (pull request 46) are in pull request 47, and I don't think I successfully reverted all the changes when I tried separating one branch into two. Is there a way to diff pull request 46 and 47? 47 might have everything that 46 does, with some of the additional link changes to the overview topic to make things more visible. Otherwise, I think merging 46 first and then 47 would work too.

2024-05-14 01:54 UTC, rbwatson commented
I rebased your pull request and merged #46 into this one, so I'll close #46.
Review these changes and address whatever comments remain, then when it looks ready to you, 
squash the commits and it should be ready to merge.

Thanks!

2024-05-20 14:23 UTC, rbwatson approved these changes
Rebased and squashed for merge

2024-05-20 14:23 UTC, merged