Reference: List all user last names
UWC2-APIDOC/to-do-service-public pull request #51
Opened 2024-05-13 03:24 UTC by skym97

Assignment 7.1

2024-05-13 14:42 UTC, rbwatson requested changes
You might need to modify your topic some. I don't think that this feature/syntax is supported.

Perhaps try something like, "Get users by last name" using `GET {base_url}/users?last_name=<name-to-find>`. If `last_name` is already documented, you could use `first_name`.

2024-05-13 14:42 UTC, rbwatson commented on docs/api/list_all_user_last_names.md
> +curl -X GET https://api.example.com/users/last_names
I tried this and got:
```
$ curl -X GET https://api.example.com/users/last_names
curl: (6) Could not resolve host: api.example.com
```

I then tried the local URL and got:
```
$ curl -X GET http://localhost:3000/users/last_names
Not Found
```
Are you sure this is the correct syntax and that this operation is supported?

2024-05-13 14:42 UTC, rbwatson commented on docs/api/users-get-all-users.md
> +[List all user last names](api/list_all_user_last_names.md)
```suggestion
[List all user last names](list_all_user_last_names.md)
```
The URL in your file is a relative URL, so the link that results from your code is:

```
https://rbwatson.github.io/to-do-service-public/api/api/list_all_user_last_names.md
```

If the file that you're linking to is in the same folder as you're linking from, all you need to put is the filename.

2024-05-20 14:50 UTC, rbwatson requested changes
Rebased the branch to review.
Please update the topic to document a supported feature. For example, Get users by last_name.
And then test, squash, and request a review of the new topic.

2024-05-26 14:03 UTC, rbwatson commented
I didn't see that you were working on this.
I just rebased your pull-request/feature branch, so be sure to update your fork & clone, before you continue.
Sorry for the confusion!
--bob

2024-05-27 02:17 UTC, skym97 commented
Apologies for the delay. Was sick the past couple of weeks with other things I needed to tend to (while being sick on top of that).

I made the changes requested (I believe) and I hope I rebased correctly with the edits. Please let me know if I haven't.

2024-05-28 20:29 UTC, rbwatson approved these changes
Rebased and squashed for merge.
Updated links to pass link-check.

2024-05-28 20:29 UTC, merged