week7-assignment
UWC2-APIDOC/to-do-service-public pull request #60
Opened 2024-05-14 00:31 UTC by raginimangla

Added API reference topic - [Create a task](#tasks-create-task) and tutorial topic - [Get tasks for a user](tutorials/get-tasks-for-a-user).

2024-05-14 01:37 UTC, rbwatson requested changes
Good topics! Just some questions in the files to resolve.

But your feature branch is out of sync, so you'll need to:
1. Sync your fork
2. Update the main branch on your clone
3. Rebase your feature branch, which might require that you resolve some merge conflicts and review the changes in your editor during the rebase. 
4. Force push the updated feature branch to your fork.
5. Build the docs from your feature branch and review them to make sure they look correct.
6. Update the files to address the comments, and commit those changes.
7. Squash your new commits in the feature branch and force push the branch to your fork.

Then your pull request will be ready to merge.

Thanks!

2024-05-14 01:37 UTC, rbwatson commented on docs/api/tasks-create-task.md
> +
What about `warning` and `user_id`?

2024-05-14 01:37 UTC, rbwatson commented on docs/api/tasks-create-task.md
> +    }
What about `warning` and `user_id`?

2024-05-14 01:37 UTC, rbwatson commented on docs/api/tasks-create-task.md
> +    }
What about `warning` and `user_id`?

2024-05-14 01:37 UTC, rbwatson commented on docs/tutorials/get-tasks-for-a-user
> +        {
The tasks in this response have different `user_id` values. That seems odd.

2024-05-14 01:37 UTC, rbwatson commented on docs/tutorials/get-tasks-for-a-user
> +    - **URL**: `{{base_url}}/tasks?user_id=<user_id>`
```suggestion
    - **URL**: `{{base_url}}/tasks?user_id=1`
```
You should use a specific `user_id` in the tutorial so they get a response that matches your documentation. You can then explain that they can change the `user_id` value as needed in future calls.

Also the double braces filter out the text between them. 
See `docs/tutorials/get-a-user-by-name.md` for examples of markup that makes them visible, again.

2024-05-14 01:37 UTC, rbwatson commented on docs/tutorials/get-tasks-for-a-user
> +
```suggestion

## Next steps

```
To separate the tutorial from the next steps.

2024-05-15 01:58 UTC, rbwatson commented
If this pull request was replaced by #74, please close this one.

2024-05-15 02:47 UTC, closed without merging

2024-05-15 02:47 UTC, raginimangla commented
closing this as new pr #74 was created